In [2]:
import numpy as np

In [4]:
a = np.array([1, 2])

In [5]:
print(a)

[1 2]


In [6]:
b = np.array([3,4])

In [7]:
print(a+b)

[4 6]


In [8]:
print(a/b)

[0.33333333 0.5       ]


In [9]:
print(a-b)

[-2 -2]


In [10]:
print(a*b)

[3 8]


In [11]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(A.shape)

(3, 3)


In [14]:
print(A.dtype)

int32


shape生成矩阵的形状
dtype查看举证的数据类型

下面是广播的例子：

In [16]:
print(A*10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [17]:
A=np.array([[1,2], [3, 4]])

In [18]:
B = np.array([10,20])

In [19]:
print(A * B) # 此处的乘法不是矩阵乘法，而是简单的一对一相乘

[[10 40]
 [30 80]]


综上所述：因为NumPy有广播功能，所以不同形状的举证之间可以进行运算。

###  1.5.6 元素的访问

In [20]:
X = np.array([[15, 48], [31, 45], [43, 64]])

In [21]:
print(X)

[[15 48]
 [31 45]
 [43 64]]


In [22]:
X[0] # 访问举证的第一行

array([15, 48])

In [23]:
X[0][1] # 访问矩阵的(0,1)的元素

48

In [27]:
for x in X:  # 遍历矩阵的所有元素
    print(x)

[15 48]
[31 45]
[43 64]


In [28]:
X = X.flatten() # 将机组恶化你转换为一维数组

In [29]:
X

array([15, 48, 31, 45, 43, 64])

In [30]:
X[0]

15

In [31]:
X[np.array([0, 2, 4])]  # 获取索引为0、2、4的元素

array([15, 31, 43])

In [32]:
X > 15  # 判断数据是否大于15

array([False,  True,  True,  True,  True,  True])

In [34]:
X[X>15] # 筛选出大于15的元素

array([48, 31, 45, 43, 64])

In [35]:
X = np.array([[15, 48], [31, 45], [43, 64]])
X>15

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [36]:
X[X>15]

array([48, 31, 45, 43, 64])

综上所述：矩阵可以利用条件判断（例如X>15）其中是否满足条件，结果为true或false。
而用矩阵加索引的方式可以筛选满足条件的元素，X[X>15]